config-gen:
  fullnameOverride: "fina"

  extraConfigMaps:
    config-{{ SERVICE_NAME }}:
      # === py_logs (логирование) ===
      APP_NAME_ENV_LINK: "APP_NAME"
      APP_NAME: "fina"
      PROJECT_CODE: "FINA.PREPROD"
      LOGSTASH_LOG_HOST: "sv-mcrsrv-elk-04.sberinsur.local"

      # === TODO: Добавь свои env vars ===

      # === Vault (только для K8s!) ===
      VAULT_URL: "https://vault.dev.sberinsur.local"
      VAULT_ENGINE: "ai"
      VAULT_SECRET_PATH: "agent/product/{{ SERVICE_NAME }}"

  extraSecrets:
    secret-change-me: {}
  serviceAccount:
    create: false
