config-gen:
  fullnameOverride: "fina"

  extraConfigMaps:
    config-fina:
      # === py_logs (логирование) ===
      APP_NAME_ENV_LINK: "APP_NAME"
      APP_NAME: "fina"
      PROJECT_CODE: "FINA.DEV"
      LOGSTASH_LOG_HOST: "sv-mcrsrv-elk-04.sberinsur.local"

      # === TODO: Добавь свои env vars ===

      # === Vault (только для K8s!) ===
      VAULT_URL: "https://vault.dev.sberinsur.local"
      VAULT_ENGINE: "ai"
      VAULT_SECRET_PATH: "agent/product/fina/test"
